import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { Provider } from "react-redux";
import { reduxStore } from "@/redux/store";
import StoreProvider from "./storeProvider";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fontSans.className+" overflow-hidden"}>
        {/* <Provider store={reduxStore}>{children}</Provider> */}
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
